[project]
name = "tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yuta Suzuki", email = "suzuki7yuta@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "mavlink",
    "pyserial>=3.5",
]

[project.scripts]
tools = "tools:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
mavlink = { url = "https://github.com/TeamMeltingPoppo/mavlink-python/releases/download/0.6.5/mavlink-0.6.5-py3-none-any.whl" }
